# PG !!!
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'pg'
#
development:
    adapter: postgresql
    encoding: unicode
    host: 
    database: 
    pool: 5
    username: 
    password: 
    port: 5432
